### ISSUE TITLE
So many WARNINGS while running

### ISSUE THREAD

**Issue by LeBronBao** [deepmind/leo#10]
I have installed required libs, and tensorflow version is 0.13 and tensorflow-probability version is 0.6. However, when I ran runner.py, there appeared so many WARNINGs showing that some usages of tensorflow are deprecated and will be removed in a future version. And there was nothing about expected results. How can I solve this problem? Thanks a lot.

**Comment by sygi** [comment]
Hi,
thank you for raising the concern. TF is undergoing a big rewrite at the moment, which contains a lot of the functions being deprecated. The upcoming TF2 is not yet stable. According to my knowledge, there's no functionality removal within the 1.X versions, so the code should work as expected with any TF version >= 1.12 and <2.0

If you're bothered by the warnings, you can disable them, setting:
```
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
```
see [SO thread](https://stackoverflow.com/questions/35911252/disable-tensorflow-debugging-information).

Regarding
> And there was nothing about expected results. How can I solve this problem?

I'm not sure what kind of results you are looking for? The README provides the test accuracies we got by running the code. Are you looking for something else?
