### ISSUE TITLE
Where is the 'outer loop' mentioned in the paper?

### ISSUE THREAD

**Issue by SunnyWangGitHub** [deepmind/leo#11]
Hi! I have a small problem...
In the code, I only saw the inner loop', and did not find the implementation of N-way K-shot classification tasks, such as using wrn-28-10 to do image classification?
Maybe it's in the raw_data["embeddings"] of the embeddings you provided?Already processed?

**Comment by andreirusu** [comment]
Thanks for your question! Appendix B.2 gives some details about training feature embeddings. Are you asking how we trained the embeddings? If that's so, then please have a look at the appendix.

If you are asking about the "outer loop", please have a look at section 2.3.4. in the pape where the meta-loss is described.

If you're asking about the code which produces N-way K-shot problem, instances, then have a look at the get_instance utility function: https://github.com/deepmind/leo/blob/master/data.py#L169


Feel free to come back with more questions!
