### ISSUE TITLE
Wrong instruction when running python runner.py -- --data_path=$EMBEDDINGS

### ISSUE THREAD

**Issue by ggaziv** [deepmind/leo#2]
Hi,

In my experiments that middle empty '--' basically tells the flags parser to ignore everything that comes after, including the important data_path definition.

The result will be failing due default 'None' data_path defined in the config file.

Guy

**Comment by sygi** [comment]
Thank you for spotting the error. Apparently interactive python (which I have aliased to `python`) requires these double dash.
