### ISSUE TITLE
Incompatibility with Python 3

### ISSUE THREAD

**Issue by ggaziv** [deepmind/leo#3]
Hi,

I could not find any reference to necessary python version.
However it appears that python2.7 was counted on.
For Python 3 at least the following is required:
- Add in pickle.load encoding='latin1' else ASCII is assumed.
- Change iteritems to items.

**Comment by dhanajitb** [comment]
Yes, it would be nice if the versions of the other dependencies are mentioned as well.

**Comment by sygi** [comment]
Yeah, that's correct, at the moment the code works only with python2.7. I will update it to work with python3 soon.
