### ISSUE TITLE
ModuleNotFoundError: No module name 'tensorflow_probability'

### ISSUE THREAD

**Issue by ggaziv** [deepmind/leo#4]
Hi,

I think installing this module is required since it is imported in model.py.

Guy

**Comment by sygi** [comment]
Yeah, thank you for spotting the error.

**Comment by ljjcoder** [comment]
@ @ggaziv @sygi ,hi could you tell me which version of tensorflow and tensorflow_probability are used by you? I install tensorflow=1.12.0 and  tensorflow_probability0.5.0. when i run the code, I get a error message like"AttributeError: module 'tensorflow_core.compat.v2.math' has no attribute 'xlog1py'”.
