### ISSUE TITLE
'LEO' object has no attribute 'trainable_variables'

### ISSUE THREAD

**Issue by ggaziv** [deepmind/leo#5]
Hi,

I think this field was never defined/initialized in model.py.

Guy

**Comment by sygi** [comment]
Hello,
`LEO` object subclasses `sonnet.AbstractModule`, which defines `trainable_variables` [here](https://github.com/deepmind/sonnet/blob/00612ca3178964d86b556e062694d808ff81fcca/sonnet/python/modules/base.py#L603).
