### ISSUE TITLE
Code for training of image embeddings

### ISSUE THREAD

**Issue by nupurkmr9** [deepmind/leo#6]
Hi, Can you share the code and hyperparameters used for getting the pre-trained image embeddings (that you have released as zip)?

**Comment by andreirusu** [comment]
We have added as much information as we could think of to the appendix. There are many good codebases out there for training WRN and similar models, and we encourage you to try that out. We have largely followed the methodology from Qiao et. al, and their code is online, although it also required some modifications to reproduce exactly their setup. Please have a look: https://github.com/joe-siyuan-qiao/FewShot-CVPR

**Comment by ZhenLiuBuaa** [comment]
> Hi, Can you share the code and hyperparameters used for getting the pre-trained image embeddings (that you have released as zip)?

hello，have you found open source WRCN 28-10 model?

**Comment by nupurkmr9** [comment]
Yeah, We were able to replicate the results using the information given in the appendix of the paper. Thanks a lot.
