### ISSUE TITLE
EMBEDDINGS Proper export

### ISSUE THREAD

**Issue by MichaelMMeskhi** [deepmind/leo#7]
In the README.md for storing `embeddings` path you have:
```
$ EMBEDDINGS=`pwd`/embeddings
``` 

Change to:

```
$ export EMBEDDINGS=`pwd`/embeddings
```

**Comment by sygi** [comment]
Thank you for your suggestion. As you probably know, exporting the variable will make it available in the subprocesses of a given shell. I don't like this: I think it's up to the shell to provide the path to the embeddings to the python script, but the python script shouldn't need to look into the environment variables.

**Comment by MichaelMMeskhi** [comment]
Makes sense. I didn't see it this way.
