### ISSUE TITLE
Test and accuracy problem

### ISSUE THREAD

**Issue by banjuanshua** [deepmind/leo#9]
Thanks for your great work. When I run in test mode, it happens a AssertionError.
`Traceback (most recent call last):
  File "runner.py", line 213, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "runner.py", line 208, in main
    run_training_loop(FLAGS.checkpoint_path)
  File "runner.py", line 193, in run_training_loop
    assert not FLAGS.checkpoint_steps
AssertionError`

If I annotate 'assert not FLAGS.checkpoint_steps', I can only get 75% acc in test dataset.

**Comment by sygi** [comment]
Hi,
To run the code in the evaluation mode, you need to set the `checkpoint_path` to the place you saved the model checkpoint, `evaluation_mode=True` and `checkpoint_steps=0` to prevent corrupting the checkpoint with your evaluation.

Does that solve the issue?

**Comment by andreirusu** [comment]
I am assuming this is resolved. Please open the issue if that's not the case.

**Comment by EternalWang** [comment]
I also get only 75% acc in test dataset, while I have set the `checkpoint_path` to the saved model checkpoint,` evaluation_mode=True` and `checkpoint_steps=0`.
